---
openapi: 3.0.3
info:
  title: Accounts
  version: 1.0.1
  termsOfService: https://example.com/tos
  contact:
    name: Example Support
    email: support@example.com
    url: support.example.com
  description: API to access account information
  license: 
    name: BSD-1-Clause
    url: https://opensource.org/license/bsd-1-clause/
servers:
  - url: "{{url}}"

paths:
  /accounts/create:
    post:
      summary: Create
      description: Create
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Accounts'
              type: object
              properties:
                holder:
                  description: Account holder
                  type: string
                  example: "{{customerId}}"
                type:
                  description: Account holder
                  type: string
                  example: "{{$randomBankAccountName}}"
            example:
              holder: "{{customerId}}"
              type: "{{$randomBankAccountName}}"
      responses:
        "200":
          description: "this is some content"
        "500":
          description: "Internal server error"
  "/accounts/{accountNumber}/overview":
    get:
      summary: Overview
      description: Overview
      operationId: overview
      responses:
        "200":
          description: ""
        "500":
          description: "Internal server error"
    parameters:
      - name: accountNumber
        description: UUID for a customer account
        example: 1234567
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/Accounts'
          type: string
  "/accounts/{accountNumber}/statement/date":
    get:
      tags:
        - Statement
      summary: Date
      description: Date
      operationId: date
      requestBody:
        content:
          application/form-urlencoded:
            schema:
              $ref: '#/components/schemas/Accounts'
              type: object
              properties:
                from:
                  description: past date
                  type: string
                  example: "{{$randomDatePast}}"
                to:
                  description: recent date
                  type: string
                  example: "{{$randomDateRecent}}"
            example:
              from: "{{$randomDatePast}}"
              to: "{{$randomDateRecent}}"
      responses:
        "200":
          description: 200 OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                $ref: '#/components/schemas/Accounts'
                type: string
                example: "*"
            Connection:
              schema:
                $ref: '#/components/schemas/Accounts'
                type: string
                example: close
            Content-Encoding:
              schema:
                $ref: '#/components/schemas/Accounts'
                type: string
                example: gzip
            Date:
              schema:
                $ref: '#/components/schemas/Accounts'
                type: string
                example: "Mon, 14 Jun 2021 14:30:25 GMT"
            ETag:
              schema:
                $ref: '#/components/schemas/Accounts'
                type: string
                example: "W/\"96-S/5iQ2y1qqIInh5BwoPc+chvDJU\""
            Server:
              schema:
                $ref: '#/components/schemas/Accounts'
                type: string
                example: nginx
            Transfer-Encoding:
              schema:
                $ref: '#/components/schemas/Accounts'
                type: string
                example: chunked
            Vary:
              schema:
                $ref: '#/components/schemas/Accounts'
                type: string
                example: Accept-Encoding
            X-RateLimit-Limit:
              schema:
                $ref: '#/components/schemas/Accounts'
                type: string
                example: "120"
            X-RateLimit-Remaining:
              schema:
                $ref: '#/components/schemas/Accounts'
                type: string
                example: "119"
            X-RateLimit-Reset:
              schema:
                $ref: '#/components/schemas/Accounts'
                type: string
                example: "1623681083"
            x-srv-span:
              schema:
                $ref: '#/components/schemas/Accounts'
                type: string
                example: v=1;s=210e5b055e5bd71e
            x-srv-trace:
              schema:
                $ref: '#/components/schemas/Accounts'
                type: string
                example: v=1;t=d33d68b932344fce
          content:
            text/plain:
              examples:
                200 OK:
                  value: "{\n    \"period\": {\n        \"from\": \"{{$randomDatePast}}\",\n        \"to\": \"{{$randomDateRecent}}\"\n    },\n    \"balance\": {\n        \"opening\": {{$randomPrice}},\n        \"closing\": {{$randomPrice}}\n    },\n    \"money\": {\n        \"in\": {{$randomPrice}},\n        \"out\": {{$randomPrice}}\n    },\n    \"transactions\": [\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        }\n    ]\n}"
        "500":
          description: "Internal server error"
    parameters:
      - name: accountNumber
        description: UUID for a customer account
        example: 1234567
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/Accounts'
          type: string
  "/accounts/{accountNumber}/statement/latest":
    get:
      tags:
        - Statement
      summary: Latest
      description: Latest
      operationId: latest
      responses:
        "200":
          description: ""
        "500":
          description: "Internal server error"
    parameters:
      - name: accountNumber
        description: UUID for a customer account
        example: 1234567
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/Accounts'
          type: string

tags:
  - name: Statement

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    Accounts:
      type: object
      description: Accounts schema

security:
  - BasicAuth : []